---
# WHY bother creating homedirs and manually copying /etc/skel?
# This would happen automatically on first login but this role
# wants to preinstall ssh keys for users into their homedirs before
# their first login, as a convenience. Therefore their homedirs
# must already exist before first login OR we would need to store
# ssh authorized keys in another location and point sshd at it.
# So a couple of tasks to precreate HOME, populate skel, and install keys
- name: usermanagement - Create home directories for directory users
  ansible.builtin.file:
    path: /home/{{ item.name }}
    state: directory
    owner: '{{ item.name }}'
    group: '{{ item.name }}'
    mode: '0700'
  loop: '{{ umn_user_management_permitted_users }}'
  tags:
    - usermanagement
  register: umn_user_management_homedirs_created

- name: usermanagement - Populate home directories from /etc/skel
  ansible.builtin.copy:
    src: /etc/skel/.
    dest: /home/{{ item.name }}/
    remote_src: true
    owner: '{{ item.name }}'
    group: '{{ item.name }}'
  loop: '{{ umn_user_management_permitted_users }}'
  loop_control:
    index_var: idx
  # Only copy /etc/skel the first time
  when: umn_user_management_homedirs_created.results[idx].changed
  tags:
    - usermanagement

- name: usermanagement - Create sudoers files for directory users
  community.general.sudoers:
    name: ansible-sudoers-ad-user-{{ item.name }}
    user: '{{ item.name }}'
    validation: required
    commands: ALL
    nopassword: true
  loop: '{{ umn_user_management_permitted_users }}'
  when: (item.sudo|default(False)) == True and (item.revoke|default(False)) == False
  tags:
    - usermanagement
    - sudoers

- name: usermanagement - Create sudoers files for directory groups
  community.general.sudoers:
    name: ansible-sudoers-ad-group-{{ item.name }}
    group: '{{ item.name }}'
    validation: required
    commands: ALL
    nopassword: true
  loop: '{{ umn_user_management_permitted_groups }}'
  when: (item.sudo|default(False)) == True and (item.revoke|default(False)) == False
  tags:
    - usermanagement
    - sudoers

- name: usermanagement - Remove sudoers privileges for revoked or non-sudo users
  community.general.sudoers:
    name: ansible-sudoers-ad-user-{{ item.name }}
    state: absent
  loop: '{{ umn_user_management_directory_users }}'
  when: (item.sudo|default(False)) == False or (item.revoke|default(False)) == True

- name: usermanagement - Remove sudoers privileges for revoked or non-sudo groups
  community.general.sudoers:
    name: ansible-sudoers-ad-group-{{ item.name }}
    state: absent
  loop: '{{ umn_user_management_directory_groups }}'
  when: (item.sudo|default(False)) == False or (item.revoke|default(False)) == True

- name: usermanagement - Install SSH keys for directory users
  ansible.posix.authorized_key:
    user: '{{ item.name }}'
    # Note: outer double, inner single quotes needed for this to work
    # correctly in authorized_keys
    key: "{{ item.authorized_keys | default([]) | list | flatten | join('\n') }}"
    state: present
    exclusive: true
    manage_dir: true
  loop: '{{ umn_user_management_permitted_users }}'
  tags:
    - usermanagement
